### ISSUE TITLE
Auto field gets updated

### ISSUE THREAD

**Issue by jim108dev** [Kamirus/purescript-selda#42] opened 2021-02-06 13:59 UTC
Hi!
my `userTable` has
```purescript
userTable :: Table ( bio ∷ Maybe LongString , email ∷ ShortString , id ∷ Auto Int , image ∷ Maybe LongString , password ∷ LongString , username ∷ ShortString )
```

I have tried to do an update
```
update :: Pool -> Raw -> UserId -> Aff (Either InputError User)
update pool raw id =
  withConnection pool
    ( \conn ->
        runSelda conn do
          S.update userTable
            (\r -> r.id .== litPG id)
            ( \r ->
                r
                  { bio = litPG raw.bio
                  , email = litPG raw.email
                  , image = litPG raw.image
                  , password = litPG raw.password
                  , username = litPG raw.username
                  }
            )
          S.query $ selectById id
    )
    >>= validate
```
And I get
```log
Error: (ProgrammingError { code: "428C9", column: "", constraint: "", dataType: "", detail: "Column \"id\" is an identity column defined as GENERATED ALWAYS.", file: "rewriteHandler.c", hint: "", internalPosition: "", internalQuery: "", line: "827", message: "column \"id\" can only be updated to DEFAULT", position: "", routine: "rewriteTargetListIU", schema: "", severity: "ERROR", table: "", where_: "" })
```

`logUpdate` shows:
```text
UPDATE "user" SET username = $2, password = $3, image = $4, id = id, email = $5, bio = $6 WHERE (id = $1)
[3,"jim","$2a$06$cfxV0SUgZU60hPdu9sSptOHDkG7VT2VjCxSKnhM0ivRb6abHepnDe",null,"jim@jjim.jim","I work at statefarm"]
```

```purescript
logUpdate ∷
  forall t s r m.
  TableToColsWithoutAlias s t r =>
  GetCols r =>
  MonadEffect m =>
  Table t → ({ | r } → Col s Boolean) → ({ | r } → { | r }) → m Unit
logUpdate table pred up = do
  let
    { strQuery, params } = showPG $ showUpdate table pred up
  log strQuery
  log $ unsafeStringify params
  log ""
```

I don't know the full functionality. Please correct me if I am doing things awfully complicated. It would be nice to have:
- Easier generic logging of the update, insert ..., not me replicating every param for every command.
- Update returning like insert returning.

Thanks.

**Comment by Kamirus** [comment] 2021-02-06 16:29
> `Easier generic logging of the update, insert ..., not me replicating every param for every command.`

Do you mean including a function like `logUpdate` in the library or something extra?

> `Update returning like insert returning.`

Could you open an issue for it?

Could you provide how you defined `id` column, I see that `update` needs to be changed, as you can see in the generated INSERT there's `id = id` which shouldn't be there in case insertions on `id` are not allowed.

**Comment by Kamirus** [comment] 2021-02-06 17:34
PR #43 fixes in part - not updated columns are not present in the SET clause.
But `Auto`/`Default` still does not affect update statements - it might be discussed whether `Auto` columns should not be allowed in `UPDATE`'s `SET` clause - thus a user can still change `id` in this case.

**Comment by Kamirus** [comment] 2021-05-22 13:44
#43 is merged now. @jim108dev is it enough to close this issue or is there something more to be done?

**Comment by jim108dev** [comment] 2021-06-06 11:15
Hey! Long time no see. @Kamirus `query1_` is gone in the newest version. That's a pity! I use this function quite often. update-> return value. get encrypted value query -> next query.
Somehow the new kind/type system is broken in the latest version of PureScript. The variable records don't work anymore. https://github.com/purescript/purescript/issues/4105 . Hopefully this will be fixed soon.

**Comment by jim108dev** [comment] 2021-06-06 11:18
Hey! Long time no see. @Kamirus query1_ is gone in the newest version. That's a pity! I use this function quite often. update-> return value. get encrypted value query -> next query.

**Comment by Kamirus** [comment] 2021-06-07 09:06
Hi, yes that was quite some time :smirk: 
Here's the `query1_` implementation in case you want to define it yourself.
```purescript
-- | Throws `ConversionError ∷ PGError` in case of no results.
query1_
  ∷ ∀ o i m
  . GenericQuery BackendPGClass m i o
  ⇒ MonadSeldaPG m
  ⇒ FullQuery B { | i } → m { | o }
query1_ = query1 >=> maybe (throwError err) pure
  where err = ConversionError "Cannot execute `query1_`: result array is empty"
```

I don't remember the exact reason why it got removed (maybe @paluh has some insights), but it was probably due to the "less-typesafe" nature of it as it throws `ConversionError` (defined in the postgresql-client). So it almost behaves like the `head` function from Haskell.

**Comment by jim108dev** [comment] 2021-06-08 06:43
ok thanks! The update works with `SERIAL` but it does not work with `GENERATED ALWAYS AS IDENTITY`.
The postgresql wiki recommends the latter:
https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial

**Closed as completed** 2021-06-08 18:18 UTC
Labels: bug, backend-integration

**Comment by Kamirus** [comment] 2021-06-08 18:37
Update should now only include these fields that need updating - this is not ideal solution as updating `GENERATED ALWAYS AS IDENTITY` fields is allowed even for `Auto` as was intended. We can consider changing its behavior or adding another constraint like `ID` (ideally changing the name of `Auto`).

@jim108dev let me know if this issue still needs some work
